baseurl = "https://example.com/"
title = "console-demo"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "exampleSite/content/about/"
  url = "exampleSite/content/about/"

  [[params.navlinks]]
  name = "exampleSite/content/posts/"
  url = "exampleSite/content/posts/"
  
  [[params.navlinks]]
  name = "exampleSite/content/photos/"
  url = "exampleSite/content/photos/"
